### ISSUE TITLE
Table format for workshops wiki hard to edit

### ISSUE THREAD

**Issue by martinamorris** [statnet/Workshops#11]
The info looks much nicer in this format, but is a PITA to edit.  I think the drawbacks outweigh the benefits, unless we can find an easier markdown format to use.  :(

**Comment by skhan890** [comment]
Indeed, it is a PITA to edit (which is why it was taking me a while to manually edit each row the other day).

Other markdown tables are no better - in fact, plain Markdown is the easiest out of all of them. I've been using a Markdown table generator to copy/paste from Excel, and it generates the code: 
![image](https://user-images.githubusercontent.com/15852734/60404118-6546a000-9b5a-11e9-92e9-d4bcf4f1d4b5.png)

Since the table is formatted: to change it, you can copy/paste the table out into some friendly text editor (i.e. Notepad++), and it then looks more editable:

Example:
![image](https://user-images.githubusercontent.com/15852734/60404101-4516e100-9b5a-11e9-8f37-ea2ab481cecb.png)


Thoughts? Or should I revert back to the old format?

**Comment by martinamorris** [comment]
I'll run this by Steve, but I'm guessing we'll go back to the list format :(

**Comment by sgoodreau** [comment]
Yeah. Love markdown, hate markdown tables.

**Comment by skhan890** [comment]
Sounds good - I removed the tables and reverted back to the old layout.
https://github.com/statnet/Workshops/wiki
